"""empty message

Revision ID: 461d0a02479f
Revises: ad5196c0d4b6
Create Date: 2019-01-11 11:21:47.080662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '461d0a02479f'
down_revision = 'ad5196c0d4b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
